# This configuration is for a Waveshare ESP32-C6-Zero module ( https://www.waveshare.com/wiki/ESP32-C6-Zero )
#
# P1-port           C6
# -----------------------
# 1 - 5V            5V
# 2 - RTS           GPIO14
# 3 - Data GND      GND
# 4 - N/C
# 5 - TX            RX (GPIO16)
# 6 - GND           GND
#
# OBIS Codes list: https://www.promotic.eu/en/pmdoc/Subsystems/Comm/PmDrivers/IEC62056_OBIS.htm
# ESP32-C6-DevKitC-1: https://docs.espressif.com/projects/esp-dev-kits/en/latest/esp32c6/esp32-c6-devkitc-1/user_guide.html
#

esphome:
  name: compteur-ores
  friendly_name: Compteur ORES

esp32:
  board: esp32-c6-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "CHANGEME"

ota:
  - platform: esphome
    password: "CHANGEME"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Compteur-Ores Fallback Hotspot"
    password: "CHANGEME"

captive_portal:

external_components:
  - source: github://Beaky2000/esphome-p1mini@main
    components: [ p1_mini ]

switch:
  - platform: gpio
    id: p1_rts
    pin: GPIO14

light:
  - platform: esp32_rmt_led_strip
    rgb_order: RGB
    chipset: WS2812
    pin: GPIO8
    num_leds: 1
    name: "status_led"
    gamma_correct: 1.0
    color_correct: [ 100%, 60%, 50% ]
    id: status_led
    default_transition_length: 0s

script:
  - id: status_light_color
    parameters:
      param_brightness: float
      param_red: float
      param_green: float
      param_blue: float
    then:
      - light.turn_on:
          id: status_led
          brightness: !lambda return param_brightness;
          red:        !lambda return param_red;
          green:      !lambda return param_green;
          blue:       !lambda return param_blue;
          transition_length: 0s

binary_sensor:
  - platform: gpio
    id: secondary_p1_rts
    pin:
      number: GPIO2
      mode: INPUT_PULLDOWN
      inverted: false

uart:
  - id: my_uart_1
    tx_pin:
      number: GPIO16         # TX on board
      inverted: true
      mode: OUTPUT_OPEN_DRAIN
    rx_pin:
      number: GPIO17         # RX on board
      inverted: true
      mode: INPUT_PULLUP
    baud_rate: 115200
    rx_buffer_size: 512

p1_mini:
  - id: p1_mini_1
    uart_id: my_uart_1
    minimum_period: 2s
    buffer_size: 3072
    secondary_rts: secondary_p1_rts
    on_ready_to_receive:
      then:
        - switch.turn_on: p1_rts
        - lambda: id(status_light_color)->execute(0.10f, 0.0f, 0.0f, 1.0f); # Blue, 10% brightness
    on_update_received:
      then:
        - switch.turn_off: p1_rts
    on_update_processed:
      then:
        if:
          condition:
            wifi.connected:
          then:
            - lambda: id(status_light_color)->execute(0.10f, 0.0f, 1.0f, 0.0f); # Green, 10% brightness
          else:
            - lambda: id(status_light_color)->execute(0.10f, 1.0f, 0.0f, 0.8f); # Purple, 10% brightness
    on_communication_error:
      then:
        - switch.turn_off: p1_rts
        - lambda: id(status_light_color)->execute(0.50f, 1.0f, 0.0f, 0.0f); # Red, 10% brightness

sensor:
- platform: wifi_signal
  name: "WiFi Signal"
  update_interval: 10s
- platform: p1_mini
  p1_mini_id: p1_mini_1
  obis_code: "1.8.1"
  name: "Cumulative Active Import (Peak hours)"
  unit_of_measurement: kWh
  accuracy_decimals: 3
  state_class: "total_increasing"
  device_class: "energy"
  id: p1_181
- platform: p1_mini
  p1_mini_id: p1_mini_1
  obis_code: "1.8.2"
  name: "Cumulative Active Import (Off-peak hours)"
  unit_of_measurement: kWh
  accuracy_decimals: 3
  state_class: "total_increasing"
  device_class: "energy"
  id: p1_182

#### Cumulative Import from the 1.8.0 register
#- platform: p1_mini
#  p1_mini_id: p1_mini_1
#  obis_code: "1.8.0"
#  name: "Cumulative Active Import"
#  unit_of_measurement: kWh
#  accuracy_decimals: 3
#  state_class: "total_increasing"
#  device_class: "energy"
#  id: p1_180

#### Cumulative Import as a sum of 1.8.1 and 1.8.2
- platform: combination
  type: sum
  name: "Cumulative Active Import"
  state_class: "total_increasing"
  device_class: "energy"
  sources:
    - source: p1_181
    - source: p1_182
- platform: p1_mini
  p1_mini_id: p1_mini_1
  obis_code: "2.8.1"
  name: "Cumulative Active Export (Peak hours)"
  unit_of_measurement: kWh
  accuracy_decimals: 3
  state_class: "total_increasing"
  device_class: "energy"
  id: p1_281
- platform: p1_mini
  p1_mini_id: p1_mini_1
  obis_code: "2.8.2"
  name: "Cumulative Active Export (Off-peak hours)"
  unit_of_measurement: kWh
  accuracy_decimals: 3
  state_class: "total_increasing"
  device_class: "energy"
  id: p1_282

#### Cumulative Export from the 2.8.0 register
#- platform: p1_mini
#  p1_mini_id: p1_mini_1
#  obis_code: "2.8.0"
#  name: "Cumulative Active Export"
#  unit_of_measurement: kWh
#  accuracy_decimals: 3
#  state_class: "total_increasing"
#  device_class: "energy"
#  id: p1_280

#### Cumulative Import as a sum of 2.8.1 and 2.8.2
- platform: combination
  type: sum
  name: "Cumulative Active Export"
  state_class: "total_increasing"
  device_class: "energy"
  sources:
    - source: p1_281
    - source: p1_282
- platform: p1_mini
  p1_mini_id: p1_mini_1
  obis_code: "1.7.0"
  name: "Momentary Active Import"
  unit_of_measurement: kW
  accuracy_decimals: 3
  device_class: "power"
  state_class: "measurement"
- platform: p1_mini
  p1_mini_id: p1_mini_1
  obis_code: "2.7.0"
  name: "Momentary Active Export"
  unit_of_measurement: kW
  accuracy_decimals: 3
  device_class: "power"
  state_class: "measurement"
- platform: p1_mini
  p1_mini_id: p1_mini_1
  obis_code: "21.8.0"
  name: "Cumulative Active Import in phase L1"
  unit_of_measurement: kWh
  accuracy_decimals: 3
  state_class: "total_increasing"
  device_class: "energy"
  id: p1_2180
- platform: p1_mini
  p1_mini_id: p1_mini_1
  obis_code: "41.8.0"
  name: "Cumulative Active Import in phase L2"
  unit_of_measurement: kWh
  accuracy_decimals: 3
  state_class: "total_increasing"
  device_class: "energy"
  id: p1_4180
- platform: p1_mini
  p1_mini_id: p1_mini_1
  obis_code: "61.8.0"
  name: "Cumulative Active Import in phase L3"
  unit_of_measurement: kWh
  accuracy_decimals: 3
  state_class: "total_increasing"
  device_class: "energy"
  id: p1_6180
- platform: p1_mini
  p1_mini_id: p1_mini_1
  obis_code: "22.8.0"
  name: "Cumulative Active Export in phase L1"
  unit_of_measurement: kWh
  accuracy_decimals: 3
  state_class: "total_increasing"
  device_class: "energy"
  id: p1_2280
- platform: p1_mini
  p1_mini_id: p1_mini_1
  obis_code: "42.8.0"
  name: "Cumulative Active Export in phase L2"
  unit_of_measurement: kWh
  accuracy_decimals: 3
  state_class: "total_increasing"
  device_class: "energy"
  id: p1_4280
- platform: p1_mini
  p1_mini_id: p1_mini_1
  obis_code: "62.8.0"
  name: "Cumulative Active Export in phase L3"
  unit_of_measurement: kWh
  accuracy_decimals: 3
  state_class: "total_increasing"
  device_class: "energy"
  id: p1_6280