esphome:
  name: compteur-ores
  friendly_name: Compteur Ores

substitutions:
  device_name: compteur-ores

esp32:
  board: lolin_c3_mini
  variant: esp32c3
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Compteur-Ores Fallback Hotspot"
    password: "CHANGE_ME"

captive_portal:

# Enable logging
logger:
  level: INFO              # Set to DEBUG if you are having issues!
  baud_rate: 0             # disable logging over uart

# Enable Home Assistant API
api:
  encryption:
    key: "CHANGE_ME"

ota:
  - platform: esphome
    password: "CHANGE_ME"

external_components:
  - source: github://Beaky2000/esphome-p1mini@main
    components: [ p1_mini ]

switch:
  - platform: gpio
    id: p1_rts             # Not needed if the RTS signal is not connected to a GPIO
    pin: GPIO8

light:
  - platform: esp32_rmt_led_strip
    rgb_order: RGB
    chipset: WS2812
    pin: GPIO7
    num_leds: 1
    name: "status_led"
    id: status_led
    default_transition_length: 0s

binary_sensor:
  - platform: gpio
    id: secondary_p1_rts # Currently not used, but make sure D0 is configured as input in case it is connected.
    pin:
      number: GPIO2
      mode: INPUT_PULLDOWN
      inverted: false

uart:
  - id: my_uart_1
    tx_pin:
      number: GPIO21
      inverted: true
      mode: OUTPUT_OPEN_DRAIN
    rx_pin:
      number: GPIO20
      inverted: true         # Set to false if inverting in hardware
      mode: INPUT_PULLUP     # Set to INPUT if inverting in hardware
    baud_rate: 115200
    rx_buffer_size: 512      # Probably not needed, but it is good to have some margin.
#    debug:
#      direction: BOTH
#      dummy_receiver: false
#  - id: my_uart_2
#    ...

p1_mini:
  - id: p1_mini_1
    uart_id: my_uart_1
    minimum_period: 2s       # Should be 0 (zero) if the RTS signal is not used.
    buffer_size: 3072        # Needs to be large enough to hold one entire update from the meter.
    secondary_rts: secondary_p1_rts
    on_ready_to_receive:
      then:
        - switch.turn_on: p1_rts
        - light.turn_on: 
            id: status_led
            red: 0%
            green: 100%
            blue: 0%
    on_update_received:
      then:
        - switch.turn_off: p1_rts
        - light.turn_on: 
            id: status_led
            red: 0%
            green: 0%
            blue: 100%
    on_communication_error:
      then:
        - switch.turn_off: p1_rts
        - light.turn_on: 
            id: status_led
            red: 100%
            green: 0%
            blue: 0%
#  - id: p1_mini_2
#    uart_id: my_uart_2
#    ...

sensor:
- platform: wifi_signal
  name: "${device_name} WiFi Signal"
  update_interval: 10s
- platform: p1_mini
  p1_mini_id: p1_mini_1
  obis_code: "1.8.1"
  name: "Cumulative Active Import (Peak hours)"
  unit_of_measurement: kWh
  accuracy_decimals: 3
  state_class: "total_increasing"
  device_class: "energy"
  id: p1_181
- platform: p1_mini
  p1_mini_id: p1_mini_1
  obis_code: "1.8.2"
  name: "Cumulative Active Import (Off-peak hours)"
  unit_of_measurement: kWh
  accuracy_decimals: 3
  state_class: "total_increasing"
  device_class: "energy"
  id: p1_182
- platform: combination
  type: sum
  name: "Cumulative Active Import"
  state_class: "total_increasing"
  device_class: "energy"
  sources:
    - source: p1_181
    - source: p1_182
- platform: p1_mini
  p1_mini_id: p1_mini_1
  obis_code: "2.8.1"
  name: "Cumulative Active Export (Peak hours)"
  unit_of_measurement: kWh
  accuracy_decimals: 3
  state_class: "total_increasing"
  device_class: "energy"
  id: p1_281
- platform: p1_mini
  p1_mini_id: p1_mini_1
  obis_code: "2.8.2"
  name: "Cumulative Active Export (Off-peak hours)"
  unit_of_measurement: kWh
  accuracy_decimals: 3
  state_class: "total_increasing"
  device_class: "energy"
  id: p1_282
- platform: combination
  type: sum
  name: "Cumulative Active Export"
  state_class: "total_increasing"
  device_class: "energy"
  sources:
    - source: p1_281
    - source: p1_282
#- platform: p1_mini
#  p1_mini_id: p1_mini_1
#  obis_code: "3.8.0"
#  name: "Cumulative Reactive Import"
#  unit_of_measurement: kvarh
#  accuracy_decimals: 3
#- platform: p1_mini
#  p1_mini_id: p1_mini_1
#  obis_code: "4.8.0"
#  name: "Cumulative Reactive Export"
#  unit_of_measurement: kvarh
#  accuracy_decimals: 3
- platform: p1_mini
  p1_mini_id: p1_mini_1
  obis_code: "1.7.0"
  name: "Momentary Active Import"
  unit_of_measurement: kW
  accuracy_decimals: 3
- platform: p1_mini
  p1_mini_id: p1_mini_1
  obis_code: "2.7.0"
  name: "Momentary Active Export"
  unit_of_measurement: kW
  accuracy_decimals: 3
#- platform: p1_mini
#  p1_mini_id: p1_mini_1
#  obis_code: "3.7.0"
#  name: "Momentary Reactive Import"
#  unit_of_measurement: kvar
#  accuracy_decimals: 3
#- platform: p1_mini
#  p1_mini_id: p1_mini_1
#  obis_code: "4.7.0"
#  name: "Momentary Reactive Export"
#  unit_of_measurement: kvar
#  accuracy_decimals: 3
- platform: p1_mini
  p1_mini_id: p1_mini_1
  obis_code: "21.7.0"
  name: "Momentary Active Import Phase 1"
  unit_of_measurement: kW
  accuracy_decimals: 3
- platform: p1_mini
  p1_mini_id: p1_mini_1
  obis_code: "22.7.0"
  name: "Momentary Active Export Phase 1"
  unit_of_measurement: kW
  accuracy_decimals: 3
#- platform: p1_mini
#  p1_mini_id: p1_mini_1
#  obis_code: "41.7.0"
#  name: "Momentary Active Import Phase 2"
#  unit_of_measurement: kW
#  accuracy_decimals: 3
#- platform: p1_mini
#  p1_mini_id: p1_mini_1
#  obis_code: "42.7.0"
#  name: "Momentary Active Export Phase 2"
#  unit_of_measurement: kW
#  accuracy_decimals: 3
#- platform: p1_mini
#  p1_mini_id: p1_mini_1
#  obis_code: "61.7.0"
#  name: "Momentary Active Import Phase 3"
#  unit_of_measurement: kW
#  accuracy_decimals: 3
#- platform: p1_mini
#  p1_mini_id: p1_mini_1
#  obis_code: "62.7.0"
#  name: "Momentary Active Export Phase 3"
#  unit_of_measurement: kW
#  accuracy_decimals: 3
#- platform: p1_mini
#  p1_mini_id: p1_mini_1
#  obis_code: "23.7.0"
#  name: "Momentary Reactive Import Phase 1"
#  unit_of_measurement: kvar
#  accuracy_decimals: 3
#- platform: p1_mini
#  p1_mini_id: p1_mini_1
#  obis_code: "24.7.0"
#  name: "Momentary Reactive Export Phase 1"
#  unit_of_measurement: kvar
#  accuracy_decimals: 3
#- platform: p1_mini
#  p1_mini_id: p1_mini_1
#  obis_code: "43.7.0"
#  name: "Momentary Reactive Import Phase 2"
#  unit_of_measurement: kvar
#  accuracy_decimals: 3
#- platform: p1_mini
#  p1_mini_id: p1_mini_1
#  obis_code: "44.7.0"
#  name: "Momentary Reactive Export Phase 2"
#  unit_of_measurement: kvar
#  accuracy_decimals: 3
#- platform: p1_mini
#  p1_mini_id: p1_mini_1
#  obis_code: "63.7.0"
#  name: "Momentary Reactive Import Phase 3"
#  unit_of_measurement: kvar
#  accuracy_decimals: 3
#- platform: p1_mini
#  p1_mini_id: p1_mini_1
#  obis_code: "64.7.0"
#  name: "Momentary Reactive Export Phase 3"
#  unit_of_measurement: kvar
#  accuracy_decimals: 3
- platform: p1_mini
  p1_mini_id: p1_mini_1
  obis_code: "32.7.0"
  name: "Voltage Phase 1"
  unit_of_measurement: V
  accuracy_decimals: 1
#- platform: p1_mini
#  p1_mini_id: p1_mini_1
#  obis_code: "52.7.0"
#  name: "Voltage Phase 2"
#  unit_of_measurement: V
#  accuracy_decimals: 1
#- platform: p1_mini
#  p1_mini_id: p1_mini_1
#  obis_code: "72.7.0"
#  name: "Voltage Phase 3"
#  unit_of_measurement: V
#  accuracy_decimals: 1
- platform: p1_mini
  p1_mini_id: p1_mini_1
  obis_code: "31.7.0"
  name: "Current Phase 1"
  unit_of_measurement: A
  accuracy_decimals: 1
#- platform: p1_mini
#  p1_mini_id: p1_mini_1
#  obis_code: "51.7.0"
#  name: "Current Phase 2"
#  unit_of_measurement: A
#  accuracy_decimals: 1
#- platform: p1_mini
#  p1_mini_id: p1_mini_1
#  obis_code: "71.7.0"
#  name: "Current Phase 3"
#  unit_of_measurement: A
#  accuracy_decimals: 1
#- platform: p1_mini
#  p1_mini_id: p1_mini_2
#  obis_code: "1.8.0"
#  name: "Cumulative Active Import"
#  unit_of_measurement: kWh
#  accuracy_decimals: 3
#  state_class: "total_increasing"
#  device_class: "energy"
#  ...
